# TensorFlow ANN Model

---



Pulak Debnath (Colorado State University Global)

CSC510: Foundations of Artificial Intelligence

Instructor: Dr. L. J. Awuah

# Due Date: 06/27/2021

In this exercise, an is made to build a predictive machine learning model with multi-layer Artificial Neural Network (ANN) algorithm using TensorFlow 2.0 framework.

### Usecase:
Using the Iris Flowers dataset, build a multi-class classification model to predict the pecies of the flower, given the measures of the flower. 

### STEP 1: Data Preperation
I have mounted a driver on colab and mapped to the google drive, where I have uploaded the iris.csv dataset. The dataset is loaded into the session using Pandas library. Next, the data is prepared where, input and output variables are separated, as well as the string (class) data is converted to integers.

In [18]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow.keras.layers import Dense

# load the dataset
path = '/content/drive/MyDrive/Colab Notebooks/Data/iris.csv' 
df = pd.read_csv(path, header=None)

df.head()


0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [14]:
# X=input (all, but the last column), y=output (last column)
X, y = df.values[:, :-1], df.values[:, -1]

# convert all input to float
X = X.astype('float32')
print('X: ', X[:5,:])
# convert all string variable to integer (class variable in output matrix)
y = LabelEncoder().fit_transform(y)
print('y: ', y[:5])

X:  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
y:  [0 0 0 0 0]


### STEP 2: Training and Test set
Now split the data into training (70%) and test (30%) set 

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(105, 4) (45, 4) (105,) (45,)


#### STEP 3: Define ANN Model features
There are 4 input features.
A tensorflow.sequencial() method is used to stack the layers.
Here, two hidden layers were added, where the 1st hidden layer is defined with 10 features, and the 2nd hidden layer is defined with 8 features. The output layers is needed 3 features to classify the three iris flowers.

In [20]:
in_features = X_train.shape[1]
print(in_features)

# define model
model = tf.keras.Sequential()
model.add(Dense(10, activation='relu', input_shape=(in_features,)))
model.add(Dense(7, activation='relu'))
model.add(Dense(3, activation='softmax'))

# compile the model
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy', 
              metrics=['accuracy'])


4


### STEP 4: Train the model
To train the model, 100 epochs are selected with botch size of 25 each. 


In [23]:
# fit the model
model.fit(X_train, y_train, epochs=100, batch_size=25)

# evaluate the model 
loss, accuracy = model.evaluate(X_test, y_test)
print('Test accuracy: %.3f' %accuracy)

Epoch 1/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6446 - accuracy: 0.6762
Epoch 2/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6396 - accuracy: 0.6952
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6353 - accuracy: 0.6762
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6308 - accuracy: 0.6762
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6261 - accuracy: 0.6762
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6213 - accuracy: 0.6762
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6175 - accuracy: 0.6857
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6135 - accuracy: 0.6857
Epoch 9/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6079 - accuracy: 0.6952
Epoch 10/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6042 - accuracy: 0.7810
Epoch 11/100
5/5 [===========

### Model Evaluation
After 100 epochs, it can be observed that the loss function is tend to decrease and accuracy is tend to increase. It is possible to increase the epoches and determine the threshold where the model performance detoriates, or start overfitting. 

In [29]:
# make a prediction [Row#80]
row = [5.7,2.6,3.5,1.0]
yhat = model.predict([row])
print('Predicted: %s (class=%d)' % (yhat, np.argmax(yhat)))


Predicted: [[0.05384957 0.91866195 0.02748858]] (class=1)
